services:
  devcontainer:
    container_name: vibing-devcontainer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro